### ISSUE TITLE
Got Error playing stream

### ISSUE THREAD

**Issue by juuso123** [Hemmu/plugin.video.areena#2]
Hi,

I got this error trying to play a stream after I set the credentials.py and installed the addon and tried to play something. Any idea what could be wrong?

NOTICE: Thread BackgroundLoader start, auto delete: false
NOTICE: Thread LanguageInvoker start, auto delete: false
NOTICE: -->Python Interpreter Initialized<--
NOTICE: Thread BackgroundLoader start, auto delete: false
NOTICE: Thread LanguageInvoker start, auto delete: false
NOTICE: -->Python Interpreter Initialized<--
NOTICE: no finnish title for video
NOTICE: Thread BackgroundLoader start, auto delete: false
NOTICE: Thread LanguageInvoker start, auto delete: false
NOTICE: -->Python Interpreter Initialized<--
NOTICE: 1-2971318
NOTICE: currently

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('id',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 254, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 244, in router
                                                play_video(params['video'])
                                              File "/home/osmc/.kodi/addons/plugin.video.areena/main.py", line 185, in play_video
                                                print("Found correct publication, media id: " + publication['media']['id'])
                                            KeyError: ('id',)
                                            -->End of Python script error report<--
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.areena/?action=play&video=1-2971318]

**Comment by rasjani** [comment]
returned data does not contain  id  and crashes, so, error handling is required in the addon side.
