### ISSUE TITLE
Plugin won't start

### ISSUE THREAD

**Issue by teemue** [Hemmu/plugin.video.areena#3]
Running OpenELEC 6 on Raspberry Pi and trying to start plugin. Following error appears in log:

22:32:42 184551.890625 T:1571812416  NOTICE: Thread LanguageInvoker start, auto delete: false
22:32:43 184552.593750 T:1571812416  NOTICE: -->Python Interpreter Initialized<--
22:32:44 184553.218750 T:1571812416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name _AES
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.areena/main.py", line 10, in <module>
                                                from Crypto.Cipher import AES
                                              File "/storage/.kodi/addons/plugin.video.areena/Crypto/Cipher/AES.py", line 50, in <module>
                                                from Crypto.Cipher import _AES
                                            ImportError: cannot import name _AES
                                            -->End of Python script error report<--
22:32:44 184553.265625 T:1534063680   ERROR: GetDirectory - Error getting plugin://plugin.video.areena/

**Comment by rasjani** [comment]
addon uses a python  library which is _typically_ provided by OS itself, but its not available on OpenElec so fails(?).  Solutions: provide Crypto.Cipher\* within addon or add it as a dependency to addon.xml (if its available as a script module for Kodi)
